// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

public interface GossipResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simplekv.grpc.GossipResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  boolean hasOrigin();
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  com.simplekv.grpc.Location getOrigin();
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  com.simplekv.grpc.LocationOrBuilder getOriginOrBuilder();

  /**
   * <code>uint32 tokenIdentifier = 2;</code>
   */
  int getTokenIdentifier();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  boolean hasGenerationClock();
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  com.simplekv.grpc.GenerationClock getGenerationClock();
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder();
}
