// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

/**
 * Protobuf type {@code com.simplekv.grpc.GossipMessage}
 */
public  final class GossipMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.simplekv.grpc.GossipMessage)
    GossipMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GossipMessage.newBuilder() to construct.
  private GossipMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GossipMessage() {
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GossipMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.simplekv.grpc.Location.Builder subBuilder = null;
            if (origin_ != null) {
              subBuilder = origin_.toBuilder();
            }
            origin_ = input.readMessage(com.simplekv.grpc.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(origin_);
              origin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 26: {
            com.simplekv.grpc.GenerationClock.Builder subBuilder = null;
            if (generationClock_ != null) {
              subBuilder = generationClock_.toBuilder();
            }
            generationClock_ = input.readMessage(com.simplekv.grpc.GenerationClock.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(generationClock_);
              generationClock_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              ringState_ = com.google.protobuf.MapField.newMapField(
                  RingStateDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, com.simplekv.grpc.Location>
            ringState__ = input.readMessage(
                RingStateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            ringState_.getMutableMap().put(
                ringState__.getKey(), ringState__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipMessage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetRingState();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.simplekv.grpc.GossipMessage.class, com.simplekv.grpc.GossipMessage.Builder.class);
  }

  private int bitField0_;
  public static final int ORIGIN_FIELD_NUMBER = 1;
  private com.simplekv.grpc.Location origin_;
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  public boolean hasOrigin() {
    return origin_ != null;
  }
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  public com.simplekv.grpc.Location getOrigin() {
    return origin_ == null ? com.simplekv.grpc.Location.getDefaultInstance() : origin_;
  }
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  public com.simplekv.grpc.LocationOrBuilder getOriginOrBuilder() {
    return getOrigin();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 2;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int GENERATIONCLOCK_FIELD_NUMBER = 3;
  private com.simplekv.grpc.GenerationClock generationClock_;
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
   */
  public boolean hasGenerationClock() {
    return generationClock_ != null;
  }
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
   */
  public com.simplekv.grpc.GenerationClock getGenerationClock() {
    return generationClock_ == null ? com.simplekv.grpc.GenerationClock.getDefaultInstance() : generationClock_;
  }
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
   */
  public com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder() {
    return getGenerationClock();
  }

  public static final int RINGSTATE_FIELD_NUMBER = 4;
  private static final class RingStateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, com.simplekv.grpc.Location> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, com.simplekv.grpc.Location>newDefaultInstance(
                com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipMessage_RingStateEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.simplekv.grpc.Location.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, com.simplekv.grpc.Location> ringState_;
  private com.google.protobuf.MapField<java.lang.Integer, com.simplekv.grpc.Location>
  internalGetRingState() {
    if (ringState_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          RingStateDefaultEntryHolder.defaultEntry);
    }
    return ringState_;
  }

  public int getRingStateCount() {
    return internalGetRingState().getMap().size();
  }
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
   */

  public boolean containsRingState(
      int key) {
    
    return internalGetRingState().getMap().containsKey(key);
  }
  /**
   * Use {@link #getRingStateMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> getRingState() {
    return getRingStateMap();
  }
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
   */

  public java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> getRingStateMap() {
    return internalGetRingState().getMap();
  }
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
   */

  public com.simplekv.grpc.Location getRingStateOrDefault(
      int key,
      com.simplekv.grpc.Location defaultValue) {
    
    java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> map =
        internalGetRingState().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
   */

  public com.simplekv.grpc.Location getRingStateOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> map =
        internalGetRingState().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (origin_ != null) {
      output.writeMessage(1, getOrigin());
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(2, timestamp_);
    }
    if (generationClock_ != null) {
      output.writeMessage(3, getGenerationClock());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetRingState(),
        RingStateDefaultEntryHolder.defaultEntry,
        4);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (origin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOrigin());
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, timestamp_);
    }
    if (generationClock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGenerationClock());
    }
    for (java.util.Map.Entry<java.lang.Integer, com.simplekv.grpc.Location> entry
         : internalGetRingState().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, com.simplekv.grpc.Location>
      ringState__ = RingStateDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, ringState__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.simplekv.grpc.GossipMessage)) {
      return super.equals(obj);
    }
    com.simplekv.grpc.GossipMessage other = (com.simplekv.grpc.GossipMessage) obj;

    boolean result = true;
    result = result && (hasOrigin() == other.hasOrigin());
    if (hasOrigin()) {
      result = result && getOrigin()
          .equals(other.getOrigin());
    }
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && (hasGenerationClock() == other.hasGenerationClock());
    if (hasGenerationClock()) {
      result = result && getGenerationClock()
          .equals(other.getGenerationClock());
    }
    result = result && internalGetRingState().equals(
        other.internalGetRingState());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrigin()) {
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasGenerationClock()) {
      hash = (37 * hash) + GENERATIONCLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getGenerationClock().hashCode();
    }
    if (!internalGetRingState().getMap().isEmpty()) {
      hash = (37 * hash) + RINGSTATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetRingState().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.simplekv.grpc.GossipMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.simplekv.grpc.GossipMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.simplekv.grpc.GossipMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.simplekv.grpc.GossipMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.simplekv.grpc.GossipMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.simplekv.grpc.GossipMessage)
      com.simplekv.grpc.GossipMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetRingState();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableRingState();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.simplekv.grpc.GossipMessage.class, com.simplekv.grpc.GossipMessage.Builder.class);
    }

    // Construct using com.simplekv.grpc.GossipMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (originBuilder_ == null) {
        origin_ = null;
      } else {
        origin_ = null;
        originBuilder_ = null;
      }
      timestamp_ = 0L;

      if (generationClockBuilder_ == null) {
        generationClock_ = null;
      } else {
        generationClock_ = null;
        generationClockBuilder_ = null;
      }
      internalGetMutableRingState().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipMessage_descriptor;
    }

    @java.lang.Override
    public com.simplekv.grpc.GossipMessage getDefaultInstanceForType() {
      return com.simplekv.grpc.GossipMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.simplekv.grpc.GossipMessage build() {
      com.simplekv.grpc.GossipMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.simplekv.grpc.GossipMessage buildPartial() {
      com.simplekv.grpc.GossipMessage result = new com.simplekv.grpc.GossipMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (originBuilder_ == null) {
        result.origin_ = origin_;
      } else {
        result.origin_ = originBuilder_.build();
      }
      result.timestamp_ = timestamp_;
      if (generationClockBuilder_ == null) {
        result.generationClock_ = generationClock_;
      } else {
        result.generationClock_ = generationClockBuilder_.build();
      }
      result.ringState_ = internalGetRingState();
      result.ringState_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.simplekv.grpc.GossipMessage) {
        return mergeFrom((com.simplekv.grpc.GossipMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.simplekv.grpc.GossipMessage other) {
      if (other == com.simplekv.grpc.GossipMessage.getDefaultInstance()) return this;
      if (other.hasOrigin()) {
        mergeOrigin(other.getOrigin());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasGenerationClock()) {
        mergeGenerationClock(other.getGenerationClock());
      }
      internalGetMutableRingState().mergeFrom(
          other.internalGetRingState());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.simplekv.grpc.GossipMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.simplekv.grpc.GossipMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.simplekv.grpc.Location origin_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.Location, com.simplekv.grpc.Location.Builder, com.simplekv.grpc.LocationOrBuilder> originBuilder_;
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public boolean hasOrigin() {
      return originBuilder_ != null || origin_ != null;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public com.simplekv.grpc.Location getOrigin() {
      if (originBuilder_ == null) {
        return origin_ == null ? com.simplekv.grpc.Location.getDefaultInstance() : origin_;
      } else {
        return originBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder setOrigin(com.simplekv.grpc.Location value) {
      if (originBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        origin_ = value;
        onChanged();
      } else {
        originBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder setOrigin(
        com.simplekv.grpc.Location.Builder builderForValue) {
      if (originBuilder_ == null) {
        origin_ = builderForValue.build();
        onChanged();
      } else {
        originBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder mergeOrigin(com.simplekv.grpc.Location value) {
      if (originBuilder_ == null) {
        if (origin_ != null) {
          origin_ =
            com.simplekv.grpc.Location.newBuilder(origin_).mergeFrom(value).buildPartial();
        } else {
          origin_ = value;
        }
        onChanged();
      } else {
        originBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder clearOrigin() {
      if (originBuilder_ == null) {
        origin_ = null;
        onChanged();
      } else {
        origin_ = null;
        originBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public com.simplekv.grpc.Location.Builder getOriginBuilder() {
      
      onChanged();
      return getOriginFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public com.simplekv.grpc.LocationOrBuilder getOriginOrBuilder() {
      if (originBuilder_ != null) {
        return originBuilder_.getMessageOrBuilder();
      } else {
        return origin_ == null ?
            com.simplekv.grpc.Location.getDefaultInstance() : origin_;
      }
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.Location, com.simplekv.grpc.Location.Builder, com.simplekv.grpc.LocationOrBuilder> 
        getOriginFieldBuilder() {
      if (originBuilder_ == null) {
        originBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.simplekv.grpc.Location, com.simplekv.grpc.Location.Builder, com.simplekv.grpc.LocationOrBuilder>(
                getOrigin(),
                getParentForChildren(),
                isClean());
        origin_ = null;
      }
      return originBuilder_;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.simplekv.grpc.GenerationClock generationClock_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.GenerationClock, com.simplekv.grpc.GenerationClock.Builder, com.simplekv.grpc.GenerationClockOrBuilder> generationClockBuilder_;
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public boolean hasGenerationClock() {
      return generationClockBuilder_ != null || generationClock_ != null;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public com.simplekv.grpc.GenerationClock getGenerationClock() {
      if (generationClockBuilder_ == null) {
        return generationClock_ == null ? com.simplekv.grpc.GenerationClock.getDefaultInstance() : generationClock_;
      } else {
        return generationClockBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public Builder setGenerationClock(com.simplekv.grpc.GenerationClock value) {
      if (generationClockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        generationClock_ = value;
        onChanged();
      } else {
        generationClockBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public Builder setGenerationClock(
        com.simplekv.grpc.GenerationClock.Builder builderForValue) {
      if (generationClockBuilder_ == null) {
        generationClock_ = builderForValue.build();
        onChanged();
      } else {
        generationClockBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public Builder mergeGenerationClock(com.simplekv.grpc.GenerationClock value) {
      if (generationClockBuilder_ == null) {
        if (generationClock_ != null) {
          generationClock_ =
            com.simplekv.grpc.GenerationClock.newBuilder(generationClock_).mergeFrom(value).buildPartial();
        } else {
          generationClock_ = value;
        }
        onChanged();
      } else {
        generationClockBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public Builder clearGenerationClock() {
      if (generationClockBuilder_ == null) {
        generationClock_ = null;
        onChanged();
      } else {
        generationClock_ = null;
        generationClockBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public com.simplekv.grpc.GenerationClock.Builder getGenerationClockBuilder() {
      
      onChanged();
      return getGenerationClockFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    public com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder() {
      if (generationClockBuilder_ != null) {
        return generationClockBuilder_.getMessageOrBuilder();
      } else {
        return generationClock_ == null ?
            com.simplekv.grpc.GenerationClock.getDefaultInstance() : generationClock_;
      }
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.GenerationClock, com.simplekv.grpc.GenerationClock.Builder, com.simplekv.grpc.GenerationClockOrBuilder> 
        getGenerationClockFieldBuilder() {
      if (generationClockBuilder_ == null) {
        generationClockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.simplekv.grpc.GenerationClock, com.simplekv.grpc.GenerationClock.Builder, com.simplekv.grpc.GenerationClockOrBuilder>(
                getGenerationClock(),
                getParentForChildren(),
                isClean());
        generationClock_ = null;
      }
      return generationClockBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, com.simplekv.grpc.Location> ringState_;
    private com.google.protobuf.MapField<java.lang.Integer, com.simplekv.grpc.Location>
    internalGetRingState() {
      if (ringState_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RingStateDefaultEntryHolder.defaultEntry);
      }
      return ringState_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, com.simplekv.grpc.Location>
    internalGetMutableRingState() {
      onChanged();;
      if (ringState_ == null) {
        ringState_ = com.google.protobuf.MapField.newMapField(
            RingStateDefaultEntryHolder.defaultEntry);
      }
      if (!ringState_.isMutable()) {
        ringState_ = ringState_.copy();
      }
      return ringState_;
    }

    public int getRingStateCount() {
      return internalGetRingState().getMap().size();
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */

    public boolean containsRingState(
        int key) {
      
      return internalGetRingState().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRingStateMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> getRingState() {
      return getRingStateMap();
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */

    public java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> getRingStateMap() {
      return internalGetRingState().getMap();
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */

    public com.simplekv.grpc.Location getRingStateOrDefault(
        int key,
        com.simplekv.grpc.Location defaultValue) {
      
      java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> map =
          internalGetRingState().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */

    public com.simplekv.grpc.Location getRingStateOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> map =
          internalGetRingState().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearRingState() {
      internalGetMutableRingState().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */

    public Builder removeRingState(
        int key) {
      
      internalGetMutableRingState().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.simplekv.grpc.Location>
    getMutableRingState() {
      return internalGetMutableRingState().getMutableMap();
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */
    public Builder putRingState(
        int key,
        com.simplekv.grpc.Location value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableRingState().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 4;</code>
     */

    public Builder putAllRingState(
        java.util.Map<java.lang.Integer, com.simplekv.grpc.Location> values) {
      internalGetMutableRingState().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.simplekv.grpc.GossipMessage)
  }

  // @@protoc_insertion_point(class_scope:com.simplekv.grpc.GossipMessage)
  private static final com.simplekv.grpc.GossipMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.simplekv.grpc.GossipMessage();
  }

  public static com.simplekv.grpc.GossipMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GossipMessage>
      PARSER = new com.google.protobuf.AbstractParser<GossipMessage>() {
    @java.lang.Override
    public GossipMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GossipMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GossipMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GossipMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.simplekv.grpc.GossipMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

