// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

public interface GossipMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simplekv.grpc.GossipMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  boolean hasOrigin();
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  com.simplekv.grpc.Location getOrigin();
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  com.simplekv.grpc.LocationOrBuilder getOriginOrBuilder();

  /**
   * <code>uint32 tokenIdentifier = 2;</code>
   */
  int getTokenIdentifier();

  /**
   * <code>uint64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  boolean hasGenerationClock();
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  com.simplekv.grpc.GenerationClock getGenerationClock();
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder();

  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 5;</code>
   */
  int getRingStateCount();
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 5;</code>
   */
  boolean containsRingState(
      int key);
  /**
   * Use {@link #getRingStateMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.simplekv.grpc.Location>
  getRingState();
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 5;</code>
   */
  java.util.Map<java.lang.Integer, com.simplekv.grpc.Location>
  getRingStateMap();
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 5;</code>
   */

  com.simplekv.grpc.Location getRingStateOrDefault(
      int key,
      com.simplekv.grpc.Location defaultValue);
  /**
   * <code>map&lt;uint32, .com.simplekv.grpc.Location&gt; ringState = 5;</code>
   */

  com.simplekv.grpc.Location getRingStateOrThrow(
      int key);
}
