// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

/**
 * Protobuf type {@code com.simplekv.grpc.GossipResponse}
 */
public  final class GossipResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.simplekv.grpc.GossipResponse)
    GossipResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GossipResponse.newBuilder() to construct.
  private GossipResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GossipResponse() {
    tokenIdentifier_ = 0;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GossipResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.simplekv.grpc.Location.Builder subBuilder = null;
            if (origin_ != null) {
              subBuilder = origin_.toBuilder();
            }
            origin_ = input.readMessage(com.simplekv.grpc.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(origin_);
              origin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            tokenIdentifier_ = input.readUInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 34: {
            com.simplekv.grpc.GenerationClock.Builder subBuilder = null;
            if (generationClock_ != null) {
              subBuilder = generationClock_.toBuilder();
            }
            generationClock_ = input.readMessage(com.simplekv.grpc.GenerationClock.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(generationClock_);
              generationClock_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.simplekv.grpc.GossipResponse.class, com.simplekv.grpc.GossipResponse.Builder.class);
  }

  public static final int ORIGIN_FIELD_NUMBER = 1;
  private com.simplekv.grpc.Location origin_;
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  public boolean hasOrigin() {
    return origin_ != null;
  }
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  public com.simplekv.grpc.Location getOrigin() {
    return origin_ == null ? com.simplekv.grpc.Location.getDefaultInstance() : origin_;
  }
  /**
   * <code>.com.simplekv.grpc.Location origin = 1;</code>
   */
  public com.simplekv.grpc.LocationOrBuilder getOriginOrBuilder() {
    return getOrigin();
  }

  public static final int TOKENIDENTIFIER_FIELD_NUMBER = 2;
  private int tokenIdentifier_;
  /**
   * <code>uint32 tokenIdentifier = 2;</code>
   */
  public int getTokenIdentifier() {
    return tokenIdentifier_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATIONCLOCK_FIELD_NUMBER = 4;
  private com.simplekv.grpc.GenerationClock generationClock_;
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  public boolean hasGenerationClock() {
    return generationClock_ != null;
  }
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  public com.simplekv.grpc.GenerationClock getGenerationClock() {
    return generationClock_ == null ? com.simplekv.grpc.GenerationClock.getDefaultInstance() : generationClock_;
  }
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  public com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder() {
    return getGenerationClock();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (origin_ != null) {
      output.writeMessage(1, getOrigin());
    }
    if (tokenIdentifier_ != 0) {
      output.writeUInt32(2, tokenIdentifier_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    if (generationClock_ != null) {
      output.writeMessage(4, getGenerationClock());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (origin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOrigin());
    }
    if (tokenIdentifier_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, tokenIdentifier_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    if (generationClock_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getGenerationClock());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.simplekv.grpc.GossipResponse)) {
      return super.equals(obj);
    }
    com.simplekv.grpc.GossipResponse other = (com.simplekv.grpc.GossipResponse) obj;

    boolean result = true;
    result = result && (hasOrigin() == other.hasOrigin());
    if (hasOrigin()) {
      result = result && getOrigin()
          .equals(other.getOrigin());
    }
    result = result && (getTokenIdentifier()
        == other.getTokenIdentifier());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (hasGenerationClock() == other.hasGenerationClock());
    if (hasGenerationClock()) {
      result = result && getGenerationClock()
          .equals(other.getGenerationClock());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrigin()) {
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin().hashCode();
    }
    hash = (37 * hash) + TOKENIDENTIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getTokenIdentifier();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasGenerationClock()) {
      hash = (37 * hash) + GENERATIONCLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getGenerationClock().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.simplekv.grpc.GossipResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.simplekv.grpc.GossipResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.simplekv.grpc.GossipResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.simplekv.grpc.GossipResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.simplekv.grpc.GossipResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.simplekv.grpc.GossipResponse)
      com.simplekv.grpc.GossipResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.simplekv.grpc.GossipResponse.class, com.simplekv.grpc.GossipResponse.Builder.class);
    }

    // Construct using com.simplekv.grpc.GossipResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (originBuilder_ == null) {
        origin_ = null;
      } else {
        origin_ = null;
        originBuilder_ = null;
      }
      tokenIdentifier_ = 0;

      message_ = "";

      if (generationClockBuilder_ == null) {
        generationClock_ = null;
      } else {
        generationClock_ = null;
        generationClockBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.simplekv.grpc.MessagingService.internal_static_com_simplekv_grpc_GossipResponse_descriptor;
    }

    @java.lang.Override
    public com.simplekv.grpc.GossipResponse getDefaultInstanceForType() {
      return com.simplekv.grpc.GossipResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.simplekv.grpc.GossipResponse build() {
      com.simplekv.grpc.GossipResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.simplekv.grpc.GossipResponse buildPartial() {
      com.simplekv.grpc.GossipResponse result = new com.simplekv.grpc.GossipResponse(this);
      if (originBuilder_ == null) {
        result.origin_ = origin_;
      } else {
        result.origin_ = originBuilder_.build();
      }
      result.tokenIdentifier_ = tokenIdentifier_;
      result.message_ = message_;
      if (generationClockBuilder_ == null) {
        result.generationClock_ = generationClock_;
      } else {
        result.generationClock_ = generationClockBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.simplekv.grpc.GossipResponse) {
        return mergeFrom((com.simplekv.grpc.GossipResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.simplekv.grpc.GossipResponse other) {
      if (other == com.simplekv.grpc.GossipResponse.getDefaultInstance()) return this;
      if (other.hasOrigin()) {
        mergeOrigin(other.getOrigin());
      }
      if (other.getTokenIdentifier() != 0) {
        setTokenIdentifier(other.getTokenIdentifier());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasGenerationClock()) {
        mergeGenerationClock(other.getGenerationClock());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.simplekv.grpc.GossipResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.simplekv.grpc.GossipResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.simplekv.grpc.Location origin_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.Location, com.simplekv.grpc.Location.Builder, com.simplekv.grpc.LocationOrBuilder> originBuilder_;
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public boolean hasOrigin() {
      return originBuilder_ != null || origin_ != null;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public com.simplekv.grpc.Location getOrigin() {
      if (originBuilder_ == null) {
        return origin_ == null ? com.simplekv.grpc.Location.getDefaultInstance() : origin_;
      } else {
        return originBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder setOrigin(com.simplekv.grpc.Location value) {
      if (originBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        origin_ = value;
        onChanged();
      } else {
        originBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder setOrigin(
        com.simplekv.grpc.Location.Builder builderForValue) {
      if (originBuilder_ == null) {
        origin_ = builderForValue.build();
        onChanged();
      } else {
        originBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder mergeOrigin(com.simplekv.grpc.Location value) {
      if (originBuilder_ == null) {
        if (origin_ != null) {
          origin_ =
            com.simplekv.grpc.Location.newBuilder(origin_).mergeFrom(value).buildPartial();
        } else {
          origin_ = value;
        }
        onChanged();
      } else {
        originBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public Builder clearOrigin() {
      if (originBuilder_ == null) {
        origin_ = null;
        onChanged();
      } else {
        origin_ = null;
        originBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public com.simplekv.grpc.Location.Builder getOriginBuilder() {
      
      onChanged();
      return getOriginFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    public com.simplekv.grpc.LocationOrBuilder getOriginOrBuilder() {
      if (originBuilder_ != null) {
        return originBuilder_.getMessageOrBuilder();
      } else {
        return origin_ == null ?
            com.simplekv.grpc.Location.getDefaultInstance() : origin_;
      }
    }
    /**
     * <code>.com.simplekv.grpc.Location origin = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.Location, com.simplekv.grpc.Location.Builder, com.simplekv.grpc.LocationOrBuilder> 
        getOriginFieldBuilder() {
      if (originBuilder_ == null) {
        originBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.simplekv.grpc.Location, com.simplekv.grpc.Location.Builder, com.simplekv.grpc.LocationOrBuilder>(
                getOrigin(),
                getParentForChildren(),
                isClean());
        origin_ = null;
      }
      return originBuilder_;
    }

    private int tokenIdentifier_ ;
    /**
     * <code>uint32 tokenIdentifier = 2;</code>
     */
    public int getTokenIdentifier() {
      return tokenIdentifier_;
    }
    /**
     * <code>uint32 tokenIdentifier = 2;</code>
     */
    public Builder setTokenIdentifier(int value) {
      
      tokenIdentifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 tokenIdentifier = 2;</code>
     */
    public Builder clearTokenIdentifier() {
      
      tokenIdentifier_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.simplekv.grpc.GenerationClock generationClock_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.GenerationClock, com.simplekv.grpc.GenerationClock.Builder, com.simplekv.grpc.GenerationClockOrBuilder> generationClockBuilder_;
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public boolean hasGenerationClock() {
      return generationClockBuilder_ != null || generationClock_ != null;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public com.simplekv.grpc.GenerationClock getGenerationClock() {
      if (generationClockBuilder_ == null) {
        return generationClock_ == null ? com.simplekv.grpc.GenerationClock.getDefaultInstance() : generationClock_;
      } else {
        return generationClockBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public Builder setGenerationClock(com.simplekv.grpc.GenerationClock value) {
      if (generationClockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        generationClock_ = value;
        onChanged();
      } else {
        generationClockBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public Builder setGenerationClock(
        com.simplekv.grpc.GenerationClock.Builder builderForValue) {
      if (generationClockBuilder_ == null) {
        generationClock_ = builderForValue.build();
        onChanged();
      } else {
        generationClockBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public Builder mergeGenerationClock(com.simplekv.grpc.GenerationClock value) {
      if (generationClockBuilder_ == null) {
        if (generationClock_ != null) {
          generationClock_ =
            com.simplekv.grpc.GenerationClock.newBuilder(generationClock_).mergeFrom(value).buildPartial();
        } else {
          generationClock_ = value;
        }
        onChanged();
      } else {
        generationClockBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public Builder clearGenerationClock() {
      if (generationClockBuilder_ == null) {
        generationClock_ = null;
        onChanged();
      } else {
        generationClock_ = null;
        generationClockBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public com.simplekv.grpc.GenerationClock.Builder getGenerationClockBuilder() {
      
      onChanged();
      return getGenerationClockFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    public com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder() {
      if (generationClockBuilder_ != null) {
        return generationClockBuilder_.getMessageOrBuilder();
      } else {
        return generationClock_ == null ?
            com.simplekv.grpc.GenerationClock.getDefaultInstance() : generationClock_;
      }
    }
    /**
     * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.simplekv.grpc.GenerationClock, com.simplekv.grpc.GenerationClock.Builder, com.simplekv.grpc.GenerationClockOrBuilder> 
        getGenerationClockFieldBuilder() {
      if (generationClockBuilder_ == null) {
        generationClockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.simplekv.grpc.GenerationClock, com.simplekv.grpc.GenerationClock.Builder, com.simplekv.grpc.GenerationClockOrBuilder>(
                getGenerationClock(),
                getParentForChildren(),
                isClean());
        generationClock_ = null;
      }
      return generationClockBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.simplekv.grpc.GossipResponse)
  }

  // @@protoc_insertion_point(class_scope:com.simplekv.grpc.GossipResponse)
  private static final com.simplekv.grpc.GossipResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.simplekv.grpc.GossipResponse();
  }

  public static com.simplekv.grpc.GossipResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GossipResponse>
      PARSER = new com.google.protobuf.AbstractParser<GossipResponse>() {
    @java.lang.Override
    public GossipResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GossipResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GossipResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GossipResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.simplekv.grpc.GossipResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

