// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simplekv.grpc.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   */
  java.lang.String getHost();
  /**
   * <code>string host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
