// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

/**
 * Protobuf enum {@code com.simplekv.grpc.ReadRequestType}
 */
public enum ReadRequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CLIENT_READ = 0;</code>
   */
  CLIENT_READ(0),
  /**
   * <code>READ = 1;</code>
   */
  READ(1),
  /**
   * <code>READ_DIGEST = 2;</code>
   */
  READ_DIGEST(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CLIENT_READ = 0;</code>
   */
  public static final int CLIENT_READ_VALUE = 0;
  /**
   * <code>READ = 1;</code>
   */
  public static final int READ_VALUE = 1;
  /**
   * <code>READ_DIGEST = 2;</code>
   */
  public static final int READ_DIGEST_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ReadRequestType valueOf(int value) {
    return forNumber(value);
  }

  public static ReadRequestType forNumber(int value) {
    switch (value) {
      case 0: return CLIENT_READ;
      case 1: return READ;
      case 2: return READ_DIGEST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ReadRequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ReadRequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ReadRequestType>() {
          public ReadRequestType findValueByNumber(int number) {
            return ReadRequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.simplekv.grpc.MessagingService.getDescriptor().getEnumTypes().get(0);
  }

  private static final ReadRequestType[] VALUES = values();

  public static ReadRequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ReadRequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.simplekv.grpc.ReadRequestType)
}

