// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

public interface ReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simplekv.grpc.ReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>bytes vale = 2;</code>
   */
  com.google.protobuf.ByteString getVale();

  /**
   * <code>bytes digest = 3;</code>
   */
  com.google.protobuf.ByteString getDigest();

  /**
   * <code>uint64 executionTime = 4;</code>
   */
  long getExecutionTime();
}
