// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

public interface ReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simplekv.grpc.ReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.com.simplekv.grpc.ReadRequestType requestType = 2;</code>
   */
  int getRequestTypeValue();
  /**
   * <code>.com.simplekv.grpc.ReadRequestType requestType = 2;</code>
   */
  com.simplekv.grpc.ReadRequestType getRequestType();
}
