// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagingService.proto

package com.simplekv.grpc;

public interface WriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.simplekv.grpc.WriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>bytes value = 2;</code>
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>.com.simplekv.grpc.WriteType type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.simplekv.grpc.WriteType type = 3;</code>
   */
  com.simplekv.grpc.WriteType getType();

  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  boolean hasGenerationClock();
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  com.simplekv.grpc.GenerationClock getGenerationClock();
  /**
   * <code>.com.simplekv.grpc.GenerationClock generationClock = 4;</code>
   */
  com.simplekv.grpc.GenerationClockOrBuilder getGenerationClockOrBuilder();
}
